### ISSUE TITLE
read .navigation and update front matter with menu params

### ISSUE THREAD

**Issue by thedigicraft** [mieweb/wikiGDrive#26]
We want the option to use a  .navigation Google Document in the root folder in order to add menu parameters to each page's front matter.

The .navigation document will be an unordered list (with nested lists) that includes a link to the corresponding Google Document.  Use the `id` from that url to locate the corresponding Markdown file.

We will need to add 3 menu parameters: identifier, parent and weight; and should be appended to the front matter. 

**identifier:** Use Google Doc id of document
**parent:** Use Google Doc id of parent document
**weight:** Position in the list in starting with and in increments of 10.  Example: The third list item would be 30.

Using this unordered list as an example:

- Making a Web Site (doc id: 192jd9239djm230dj1223e)
  - Getting Started (doc id: 1239dn139fn59023nd0)

The child document (as it is currently):

```
---
title: "Getting Started"
date: 2019-12-30T21:48:20.991Z
url: "getting-started.md"
author: John Smith
id: 1239dn139fn59023nd0
source: https://drive.google.com/open?id=1239dn139fn59023nd0
---
```
An example with menu parameters appended:

```
---
title: "Getting Started"
date: 2019-12-30T21:48:20.991Z
url: "getting-started.md"
author: John Smith
id: 1239dn139fn59023nd0
source: https://drive.google.com/open?id=1239dn139fn59023nd0
menu:
  main:
    identifier: "1239dn139fn59023nd0"
    parent: "192jd9239djm230dj1223e"
    weight: 10
---
```
